name: ubuntu-22.04

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install GCC12
      shell: bash
      run:  |
            sudo apt update
            sudo apt install gcc-12 g++-12

    - name: Install dependencies
      shell: bash
      run:  |
            sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
            sudo apt install libudev-dev libopenal-dev libvorbis-dev libflac-dev
            sudo apt install libxrandr-dev libxcursor-dev libglew-dev

    - name: Build
      run: ./build-plz --used-compilers && ./build-plz --debug --asan

    - name: Tests
      run: ./build-plz --debug --asan --run tasks_test
